site_name: stack - The Haskell Tool Stack
pages:
- 'Home': README.md
- 'Guide': doc/GUIDE.md
- 'YAML configuration': doc/yaml_configuration.md
- 'FAQ': doc/faq.md
- 'Build command': doc/build_command.md
- 'Contributers guide': CONTRIBUTING.md
- 'Architecture': doc/architecture.md
- 'Dependency visualization': doc/dependency_visualization.md
- 'Docker integration': doc/docker_integration.md
- 'Install and upgrade': doc/install_and_upgrade.md
- 'Maintainer guide': doc/MAINTAINER_GUIDE.md
- 'Non-standard project initialization': doc/nonstandard_project_init.md
- 'Shell auto-complation': doc/shell_autocompletion.md
- 'Signing key': doc/SIGNING_KEY.md
- 'Changelog': ChangeLog.md
theme: readthedocs
docs_dir: '.'